sudo: required
language: generic

services:
 - docker

before_install:
 - docker build -t kylejohnstondocker/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true kylejohnstondocker/docker-react npm run test
